//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int IdUnit { get; set; }
        public string NameUnit { get; set; }
        public int TypeUnit { get; set; }
        public int Company { get; set; }
        public double Price { get; set; }
        public int Count { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual TypeUnit TypeUnit1 { get; set; }
    }
}
